---
title: "Лабораторна робота 2. Дослідницький аналіз даних"
author: "Команда №15"
output: html_notebook
---

```{r}
library("dplyr")
library("lattice")
```

```{r}
NEI <- readRDS("summarySCC_PM25.rds")
SCC <- readRDS("Source_Classification_Code.rds")
```

```{r}
q1_result <- NEI %>%
  group_by(year) %>%
  summarize(Emissions = sum(Emissions))

plot(q1_result$year, q1_result$Emissions, 
     type = "b", 
     main = "Total PM2.5 Emissions by Year",
     xlab = "Year", 
     ylab = "Total PM2.5 Emissions",
     xaxt = "n")

axis(side = 1, at = q1_result$year, labels = q1_result$year)
```

```{r}
q2_result <- NEI %>%
  filter(fips == "24510") %>%
  group_by(year) %>%
  summarize(Emissions = sum(Emissions))

plot(q2_result$year, q2_result$Emissions, 
     type = "b", 
     main = "Total PM2.5 Emissions in Baltimore by Year",
     xlab = "Year", 
     ylab = "Total PM2.5 Emissions in Baltimore",
     xaxt = "n")

axis(side = 1, at = q2_result$year, labels = q2_result$year)
```

```{r}
q3_result <- NEI %>%
  filter(fips == "24510") %>% 
  group_by(year, type) %>% 
  summarize(Emissions = sum(Emissions), .groups = "drop")

panel_function <- function(x, y, ...) {
  panel.xyplot(x, y, type = "b", ...)
}

xyplot(Emissions ~ year | type, data = q3_result, layout = c(4, 1),
       scales = list(x = list(at = unique(q3_result$year)), y = list(relation = "same")),
       panel = panel_function,
       xlab = "Year", ylab = "Total PM2.5 Emissions",
       main = "PM2.5 Emissions by Year and Type")
```

```{r}
coal_sources <- SCC %>% 
  filter(grepl("coal", Short.Name, ignore.case = TRUE))

q4_result <- NEI %>% 
  filter(SCC %in% coal_sources$SCC) %>%
  group_by(year) %>%
  summarize(Emissions = sum(Emissions))

plot(q4_result$year, q4_result$Emissions, 
     type = "b", 
     main = "Total PM2.5 Emissions caused by coal burning by Year",
     xlab = "Year", 
     ylab = "Total PM2.5 Emissions",
     xaxt = "n")

axis(side = 1, at = q4_result$year, labels = q4_result$year)
```

```{r}
vehicle_sources <- SCC %>% 
  filter(grepl("vehicle", Short.Name, ignore.case = TRUE))

q5_result <- NEI %>% 
  filter(SCC %in% vehicle_sources$SCC & fips == "24510") %>% 
  group_by(year) %>% 
  summarize(Emissions = sum(Emissions))

plot(q5_result$year, q5_result$Emissions, 
     type = "b", 
     main = "Total PM2.5 Emissions caused by vehicles in Baltimore by Year",
     xlab = "Year", 
     ylab = "Total PM2.5 Emissions",
     xaxt = "n")

axis(side = 1, at = q5_result$year, labels = q5_result$year)
```

```{r}
vehicle_sources <- SCC %>% 
  filter(grepl("vehicle", Short.Name, ignore.case = TRUE))

q6_result <- NEI %>%
  filter(SCC %in% vehicle_sources$SCC & (fips == "24510" | fips == "06037")) %>% 
  group_by(year, fips) %>% 
  summarize(Emissions = sum(Emissions), .groups = "drop")

unique_years <- unique(q6_result$year)

panel_function <- function(x, y, ...) {
  panel.xyplot(x, y, type = "b", ...)
}

# Create lattice plot with panel plots for each fips
xyplot(Emissions ~ year | fips, data = q6_result, layout = c(2, 1),
       scales = list(x = list(at = unique_years)),  # Customize x-axis ticks
       panel = panel_function,
       xlab = "Year", ylab = "Total PM2.5 Emissions",
       main = "PM2.5 Emissions by Year and City")
```